version: '3'
services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    build: .
    tty: true
    volumes:
      - .:/msg
    ports:
      - "3000:3000"
    depends_on:
      - db
