messages.create(content: 'あそびましょー',from_id: '1', to_id: '2',room_id: '1')
messages.create(content: 'あそびましょー2',from_id: '2', to_id: '1',room_id: '1')
messages.create(content: 'あそびましょー3',from_id: '1', to_id: '2',room_id: '1')
messages.create(content: 'あそびましょー4',from_id: '2', to_id: '1',room_id: '1')
messages.create(content: 'あそびましょー5',from_id: '1', to_id: '2',room_id: '1')
messages.create(content: 'あそびましょー6',from_id: '1', to_id: '2',room_id: '1')
